# Generated by Django 5.1.4 on 2024-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_actor_actor_name_en_actor_actor_name_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielanguages',
            name='language_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_ky',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='language_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(max_length=30, to='movie.genre'),
        ),
    ]
